dataset: "LJSpeech"

path:
  corpus_path: "/home/keon/speech-datasets/en/LJSpeech-1.1"
  preprocessed_path: "./preprocessed_data/LJSpeech"

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
    trim_top_db: 23
    segment_length: 32768
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000
    mel_fmax_loss: null
    normalize: False
  pitch:
    pitch_type: "frame" # support 'frame'
    pitch_norm: "log" # support 'standard', 'log'
    pitch_norm_eps: 0.000000001
    use_uv: True
  energy:
    feature: "frame_level" # support 'frame_level'
    normalization: True
  duration:
    beta_binomial_scaling_factor: 1.0
